
skillMetadata:
  sections:
    - name: Workout
      fields:
        - name: exercise_list
          type: text
          label: representation of your workout
          value: jumping jacks|30||,wall sits|30||,push ups|30||,abdominal crunches|30||,step up onto chair|30||,squats|30||,tricep dips|30||,plank|30||,high knees|30||,lunges|30||,push up and rotation|30||switch,side plank|30||switch
          placeholder:
        - name: rest_len
          type: number
          label: Number of seconds to rest between exercises
          value: 5
        - name: circuits
          type: number
          label: Number of times to repeat the workout
          value: 1
