
skillMetadata:
  sections:
    - name: Workout
      fields:
        - name: exercise_list
          type: text
          label: representation of your workout
          value: plank|30|1|switch,crunches|30||switch,push ups|30|15|
          placeholder:
        - name: "rest_len"
          type: number
          label: Number of seconds to rest between exercises
          value: 5
